server.port=8208
spring.application.name=service-task
spring.profiles.active=dev

spring.cloud.nacos.discovery.server-addr=${YYGH_NACOS_SERVER_ADDR:localhost:8848}

spring.rabbitmq.host=${YYGH_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${YYGH_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${YYGH_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${YYGH_RABBITMQ_PASSWORD:guest}
