# web服务访问端口
server.port=8080
#
##langchain4j测试模型
#langchain4j.open-ai.chat-model.api-key=demo
#langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
#langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
#

#DeepSeek
#langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com
#langchain4j.open-ai.chat-model.api-key=${DEEP_SEEK_API_KEY:sk-ba7900e977734a5eb16b03b8b6d248ef}
#
##DeepSeek-V3
#langchain4j.open-ai.chat-model.model-name=deepseek-v4-flash

#DeepSeek-R1 推理模型
#langchain4j.open-ai.chat-model.model-name=deepseek-reasoner

# Ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen3:0.6b

# 打印请求和响应日志
langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true

#请求和响应日志
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true


# 阿里云百炼 OpenAI 兼容接口
langchain4j.open-ai.chat-model.base-url=https://ws-hnqptj4bvbrn0vwb.cn-beijing.maas.aliyuncs.com/compatible-mode/v1

langchain4j.open-ai.chat-model.api-key=${DASHSCOPE_API_KEY:sk-ws-H.EYPLHEM.B0mm.MEUCIDfEIIrjjlqAtDyQ5Rh16cUSC0gHpN0z44a5lxaNQSBcAiEAkZTSg-f6LQIlyH55KHER5Zouy-X0o26_lWq8x0kqunQ}

langchain4j.open-ai.chat-model.model-name=qwen3.7-flash


# Wan 图片生成
# ==========================
aliyun.wan.base-url=https://ws-hnqptj4bvbrn0vwb.cn-beijing.maas.aliyuncs.com/api/v1
aliyun.wan.api-key=${DASHSCOPE_API_KEY:sk-ws-H.EYPLHEM.B0mm.MEUCIDfEIIrjjlqAtDyQ5Rh16cUSC0gHpN0z44a5lxaNQSBcAiEAkZTSg-f6LQIlyH55KHER5Zouy-X0o26_lWq8x0kqunQ}
aliyun.wan.model=wan2.7-image

# DashScope 原生协议配置（QwenChatModel）
langchain4j.dashscope.chat-model.api-key=${DASHSCOPE_API_KEY:sk-ws-H.EYPLHEM.B0mm.MEUCIDfEIIrjjlqAtDyQ5Rh16cUSC0gHpN0z44a5lxaNQSBcAiEAkZTSg-f6LQIlyH55KHER5Zouy-X0o26_lWq8x0kqunQ}
langchain4j.dashscope.chat-model.model-name=qwen-turbo

#MongoDB连接配置
spring.data.mongodb.uri=mongodb://localhost:27017/chat_memory_db

#启用日志debug级别
logging.level.root=info